import Head from 'next/head'
import Image from 'next/image'
import { Box, Container, HStack, Icon, Link } from '@chakra-ui/react'
import { FiInstagram, FiFacebook } from 'react-icons/fi'

export const Header = () => {
  return (
    <Box as="header" bg="gray.900" py="4">
      <Container maxWidth="container.xl">
        <Head>
          <title>Nail Bar SK</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HStack spacing="0" justify="space-between">
          <Image src="/logo.jpeg" alt="Nailbar" width={96} height={96} />
          <HStack spacing={2}>
            <Link boxSize={8} p={2}>
              <Icon as={FiFacebook} boxSize={4} color="brand.500" />
            </Link>
            <Link boxSize={8} p={2}>
              <Icon as={FiInstagram} boxSize={4} color="brand.500" />
            </Link>
          </HStack>
        </HStack>
      </Container>
    </Box>
  )
}
