import HHead from 'next/head'

export const Head = () => {
  return (
    <HHead>
      <title>Nail Bar SK</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <meta property="og:title" content="Nail Bar SK" />
      <meta property="og:url" content="https://nailbar.sk" />
      <meta
        property="og:description"
        content="description of your website/webpage"
      />
      <meta
        property="og:image"
        content="/_next/image?url=%2Flogo.jpeg&w=256&q=100"
      />
      <meta property="og:type" content="article" />
      <meta property="og:locale" content="sk_SK" />
    </HHead>
  )
}
